sudo: true
language: c

os: osx
osx_image:
  - xcode8
  - xcode9.2
  - xcode10.1
compiler: clang
language: java

# use the addon to do the update of homebrew, or else ruby versions get confused
addons:
  homebrew:
    update: true
    packages:
      - cmake

script:
  - CODEBUILD_SRC_DIR=`pwd` ./codebuild/common-posix.sh -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
