/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_aws_Test */

#ifndef _Included_com_amazon_aws_Test
#define _Included_com_amazon_aws_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_aws_Test
 * Method:    doIt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_amazon_aws_Test_doIt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
